package commands

import (
	"fmt"
	"strings"

	"github.com/MrFoxMcCloud/devz/internal/cli"
)

// Completion emits a shell completion script.
//
// This is the part that actually pays for the dispatcher: not having to
// remember which command exists is the whole point.
func Completion(app *cli.App) *cli.Command {
	return &cli.Command{
		Name:  "completion",
		Short: "emit a shell completion script (zsh|bash)",
		Usage: `usage: devz completion <zsh|bash>

zsh:
    devz completion zsh > ~/.claude-shared/completions/_devz
    # ensure that directory is on $fpath before compinit, then: exec zsh

bash:
    devz completion bash > ~/.local/share/bash-completion/completions/devz

The script asks the binary for its command list at completion time, so plugins
dropped on PATH complete without regenerating anything.`,
		Run: func(ctx *cli.Context, args []string) error {
			if len(args) == 0 {
				return fmt.Errorf("expected a shell (zsh or bash)")
			}
			switch args[0] {
			case "zsh":
				fmt.Fprint(ctx.Stdout, zshCompletion)
			case "bash":
				fmt.Fprint(ctx.Stdout, bashCompletion)
			case "--commands":
				// Used by the generated scripts.
				fmt.Fprintln(ctx.Stdout, strings.Join(app.Names(), "\n"))
			default:
				return fmt.Errorf("unsupported shell %q", args[0])
			}
			return nil
		},
	}
}

const zshCompletion = `#compdef devz
# Generated by: devz completion zsh

_devz() {
  local -a commands
  local line
  # Ask the binary, so plugins on PATH complete with no regeneration.
  commands=(${(f)"$(devz completion --commands 2>/dev/null)"})

  _arguments -C \
    '1: :->command' \
    '*:: :->args'

  case $state in
    command)
      _describe -t commands 'devz command' commands
      ;;
    args)
      case $line[1] in
        secrets)
          local -a subs
          subs=(unlock status list show edit)
          if (( CURRENT == 2 )); then
            _describe -t subcommands 'secrets subcommand' subs
          elif [[ $line[2] == (show|edit) ]]; then
            local -a entries
            entries=(${(f)"$(devz secrets list 2>/dev/null)"})
            _describe -t entries 'entry' entries
          fi
          ;;
        config)
          _values 'config subcommand' show path init edit
          ;;
        completion)
          _values 'shell' zsh bash
          ;;
        doctor)
          _values 'flag' --quiet
          ;;
        help)
          _describe -t commands 'devz command' commands
          ;;
      esac
      ;;
  esac
}

_devz "$@"
`

const bashCompletion = `# Generated by: devz completion bash
_devz() {
  local cur prev
  cur="${COMP_WORDS[COMP_CWORD]}"
  prev="${COMP_WORDS[COMP_CWORD-1]}"

  if [ "$COMP_CWORD" -eq 1 ]; then
    COMPREPLY=( $(compgen -W "$(devz completion --commands 2>/dev/null)" -- "$cur") )
    return
  fi

  case "${COMP_WORDS[1]}" in
    secrets)
      if [ "$COMP_CWORD" -eq 2 ]; then
        COMPREPLY=( $(compgen -W "unlock status list show edit" -- "$cur") )
      elif [ "$prev" = show ] || [ "$prev" = edit ]; then
        COMPREPLY=( $(compgen -W "$(devz secrets list 2>/dev/null)" -- "$cur") )
      fi
      ;;
    config)     COMPREPLY=( $(compgen -W "show path init edit" -- "$cur") ) ;;
    completion) COMPREPLY=( $(compgen -W "zsh bash" -- "$cur") ) ;;
    doctor)     COMPREPLY=( $(compgen -W "--quiet" -- "$cur") ) ;;
    help)       COMPREPLY=( $(compgen -W "$(devz completion --commands 2>/dev/null)" -- "$cur") ) ;;
  esac
}
complete -F _devz devz
`
