package commands

import (
	"fmt"
	"strings"

	"github.com/MrFoxMcCloud/devz/internal/cli"
)

// Completion emits a shell completion script.
//
// This is the part that actually pays for the dispatcher: not having to
// remember which command exists is the whole point.
//
// The scripts hold no lists. They ask the binary for the candidates at
// completion time, so a new command, subcommand or plugin completes without
// regenerating the script -- which matters because `go install` cannot
// regenerate it for you.
func Completion(app *cli.App) *cli.Command {
	return &cli.Command{
		Name:  "completion",
		Short: "emit a shell completion script (zsh|bash)",
		Usage: `usage: devz completion <zsh|bash>

zsh, as a file on $fpath (then: exec zsh):
    devz completion zsh > ~/.local/share/zsh/site-functions/_devz
zsh, from ~/.zshrc after compinit:
    source <(devz completion zsh)

bash:
    devz completion bash > ~/.local/share/bash-completion/completions/devz
    # or, from ~/.bashrc:  source <(devz completion bash)

The script asks the binary for its candidates at completion time, so commands,
subcommands and plugins dropped on PATH complete without regenerating it.
'devz doctor' still says when an installed copy differs from this build's.`,
		Complete: func(*cli.Context, []string) []string { return []string{"zsh", "bash"} },
		Run: func(ctx *cli.Context, args []string) error {
			if len(args) == 0 {
				return fmt.Errorf("expected a shell (zsh or bash)")
			}
			switch args[0] {
			case "zsh":
				fmt.Fprint(ctx.Stdout, zshCompletion)
			case "bash":
				fmt.Fprint(ctx.Stdout, bashCompletion)
			case "--commands":
				// Used by the generated scripts: the first word.
				fmt.Fprintln(ctx.Stdout, strings.Join(app.Names(), "\n"))
			case "--complete":
				// Used by the generated scripts: every later word. The
				// arguments are the words typed so far, after "devz".
				if candidates := complete(ctx, app, args[1:]); len(candidates) > 0 {
					fmt.Fprintln(ctx.Stdout, strings.Join(candidates, "\n"))
				}
			default:
				return fmt.Errorf("unsupported shell %q", args[0])
			}
			return nil
		},
	}
}

// complete returns the candidates for the word after words, where words[0]
// is the command. Nothing is a valid answer: the script then offers files.
func complete(ctx *cli.Context, app *cli.App, words []string) []string {
	if len(words) == 0 {
		return app.Names()
	}
	if words[0] == "help" {
		if len(words) == 1 {
			return app.Names()
		}
		return nil
	}
	cmd := app.Command(words[0])
	if cmd == nil || cmd.Complete == nil {
		return nil
	}
	return cmd.Complete(ctx, words[1:])
}

const zshCompletion = `#compdef devz
# Generated by: devz completion zsh

_devz() {
  local -a candidates
  # Ask the binary, so nothing here needs regenerating when devz gains a
  # command, a subcommand or a plugin.
  if (( CURRENT == 2 )); then
    candidates=(${(f)"$(devz completion --commands 2>/dev/null)"})
  else
    candidates=(${(f)"$(devz completion --complete "${(@)words[2,CURRENT-1]}" 2>/dev/null)"})
  fi
  if (( $#candidates )); then
    compadd -a candidates
  else
    _files
  fi
}

# As a file on $fpath, zsh runs this as the body of _devz. Sourced from an rc
# file, it only has to register the function.
if [[ ${funcstack[1]} == _devz ]]; then
  _devz "$@"
else
  compdef _devz devz
fi
`

const bashCompletion = `# Generated by: devz completion bash

_devz() {
  local cur=${COMP_WORDS[COMP_CWORD]}
  local IFS=$'\n'
  # Ask the binary, so nothing here needs regenerating when devz gains a
  # command, a subcommand or a plugin.
  if [ "$COMP_CWORD" -eq 1 ]; then
    COMPREPLY=( $(compgen -W "$(devz completion --commands 2>/dev/null)" -- "$cur") )
  else
    COMPREPLY=( $(compgen -W "$(devz completion --complete "${COMP_WORDS[@]:1:COMP_CWORD-1}" 2>/dev/null)" -- "$cur") )
    if [ ${#COMPREPLY[@]} -eq 0 ]; then
      COMPREPLY=( $(compgen -f -- "$cur") )
    fi
  fi
}
complete -F _devz devz
`
