# Generated by: devz completion bash
_devz() {
  local cur prev
  cur="${COMP_WORDS[COMP_CWORD]}"
  prev="${COMP_WORDS[COMP_CWORD-1]}"

  if [ "$COMP_CWORD" -eq 1 ]; then
    COMPREPLY=( $(compgen -W "$(devz completion --commands 2>/dev/null)" -- "$cur") )
    return
  fi

  case "${COMP_WORDS[1]}" in
    secrets)
      if [ "$COMP_CWORD" -eq 2 ]; then
        COMPREPLY=( $(compgen -W "unlock status list show edit" -- "$cur") )
      elif [ "$prev" = show ] || [ "$prev" = edit ]; then
        COMPREPLY=( $(compgen -W "$(devz secrets list 2>/dev/null)" -- "$cur") )
      fi
      ;;
    config)     COMPREPLY=( $(compgen -W "show path init edit" -- "$cur") ) ;;
    completion) COMPREPLY=( $(compgen -W "zsh bash" -- "$cur") ) ;;
    doctor)     COMPREPLY=( $(compgen -W "--quiet" -- "$cur") ) ;;
    help)       COMPREPLY=( $(compgen -W "$(devz completion --commands 2>/dev/null)" -- "$cur") ) ;;
  esac
}
complete -F _devz devz
