# Generated by: devz completion bash

_devz() {
  local cur=${COMP_WORDS[COMP_CWORD]}
  local IFS=$'\n'
  # Ask the binary, so nothing here needs regenerating when devz gains a
  # command, a subcommand or a plugin.
  if [ "$COMP_CWORD" -eq 1 ]; then
    COMPREPLY=( $(compgen -W "$(devz completion --commands 2>/dev/null)" -- "$cur") )
  else
    COMPREPLY=( $(compgen -W "$(devz completion --complete "${COMP_WORDS[@]:1:COMP_CWORD-1}" 2>/dev/null)" -- "$cur") )
    if [ ${#COMPREPLY[@]} -eq 0 ]; then
      COMPREPLY=( $(compgen -f -- "$cur") )
    fi
  fi
}
complete -F _devz devz
