# Generated by: devz completion bash
_devz() {
  local cur prev
  cur="${COMP_WORDS[COMP_CWORD]}"
  prev="${COMP_WORDS[COMP_CWORD-1]}"

  if [ "$COMP_CWORD" -eq 1 ]; then
    COMPREPLY=( $(compgen -W "$(devz completion --commands 2>/dev/null)" -- "$cur") )
    return
  fi

  case "${COMP_WORDS[1]}" in
    secrets)
      if [ "$COMP_CWORD" -eq 2 ]; then
        COMPREPLY=( $(compgen -W "unlock status list show rotate edit add map env exec cached" -- "$cur") )
      elif [ "$COMP_CWORD" -eq 3 ]; then
        case "$prev" in show|edit|rotate|map)
          COMPREPLY=( $(compgen -W "$(devz secrets list 2>/dev/null)" -- "$cur") ) ;;
        esac
      fi
      ;;
    config)     COMPREPLY=( $(compgen -W "show path init edit" -- "$cur") ) ;;
    memory)
      if [ "$COMP_CWORD" -eq 2 ]; then
        COMPREPLY=( $(compgen -W "status init" -- "$cur") )
      elif [ "${COMP_WORDS[2]}" = init ] && [[ "$cur" == -* ]]; then
        COMPREPLY=( $(compgen -W "--all --dry-run" -- "$cur") )
      else
        COMPREPLY=( $(compgen -d -- "$cur") )
      fi
      ;;
    completion) COMPREPLY=( $(compgen -W "zsh bash" -- "$cur") ) ;;
    doctor)     COMPREPLY=( $(compgen -W "--quiet --all" -- "$cur") ) ;;
    help)       COMPREPLY=( $(compgen -W "$(devz completion --commands 2>/dev/null)" -- "$cur") ) ;;
  esac
}
complete -F _devz devz
